module.exports = {
    AUTHORIZATION: 'authorization',
    BEARER: 'Bearer ',
    X_ACCESS_TOKEN: 'x-access-token',
    UNDEFINED: 'undefined',
    SERVING_TYPE: 'servingType',
    SERVING_SIZE: 'servingSize',
    FOOD_CATEGORY: 'foodCategory',
    AGE_GROUP: 'ageGroup',
    TARGET_POPULATION: 'targetPopulation',
    ONE: 1,
    ZERO: 0,
    TWO: 2,
    THREE: 3,
    FOUR: 4,
    CATEGORY: 'category',
    SWAGGER_CSS: ".swagger-ui .topbar { display: none }",
    CUSTOMER_LIST: 'customerList',
    ASC: 'ASC',
    DESC: 'DESC',
    BUSINESS_ENTITY_NAME: 'businessEntityName',
    LIMIT: 10,
    CATEGORY_ITEMS: 'categoryItems',
    EMAIL: 'email',
    PASSWORD: 'password',
    TITLE: 'title',
    DESCRIPTION: 'description',
    COMPANY_NAME: 'companyName',
    START_DATE: 'startDate',
    END_DATE: 'endDate',
    IS_FORMULATION: 'isFormulation',
    IS_LABEL_VALIDATION: 'isLabelValidation',
    TYPE: 'type'
}