module.exports = {
    AUTHORIZATION: 'authorization',
    BEARER: 'Bearer ',
    X_ACCESS_TOKEN: 'x-access-token',
    UNDEFINED: 'undefined',
    SERVING_TYPE: 'servingType',
    SERVING_SIZE: 'servingSize',
    FOOD_CATEGORY: 'foodCategory',
    AGE_GROUP: 'ageGroup',
    TARGET_POPULATION: 'targetPopulation',
    ONE: 1,
    ZERO: 0,
    TWO: 2,
    THREE: 3,
    FOUR: 4,
    CATEGORY: 'category',
}